services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: api-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    volumes:
      - app-storage:/var/www/html/storage
      - app-cache:/var/www/html/bootstrap/cache
    user: "www-data:www-data"
    networks:
      - api_network

  mongodb:
    image: mongo:latest
    container_name: api-mongodb
    restart: unless-stopped
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - api_network

volumes:
  mongodb_data:
  app-storage:
  app-cache:

networks:
  api_network:
    driver: bridge