services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: api-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
    user: "www-data:www-data"
    networks:
      - api_network

  mongodb:
    image: mongo:latest
    container_name: api-mongodb
    restart: unless-stopped
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./storage/logs:/var/www/html/storage/logs:delegated
    networks:
      - api_network

volumes:
  mongodb_data:

networks:
  api_network:
    driver: bridge