services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - .env:/var/www/.env
    ports:
      - "8080:80"
    networks:
      - api-network

  db:
    image: mongo:latest
    container_name: laravel-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - api-network

networks:
  api-network:
    driver: bridge