services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - mongodb
            - redis

    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=GlKjo1ujOEa4TXX
            - MONGO_INITDB_DATABASE=api_db
        volumes:
            - mongodb-data:/data/db
            
    redis:
        container_name: redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass "secret"
        ports:
            - 6380:6379
            
volumes:
    mongodb-data: ~
